# Generated by Django 5.0.2 on 2024-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('phone_no', models.CharField(max_length=50)),
                ('boolean_field', models.BooleanField()),
                ('date_time_field', models.DateTimeField()),
                ('email_field', models.EmailField(max_length=254)),
            ],
        ),
    ]
