# Generated by Django 5.0.2 on 2024-02-25 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_title',
            field=models.CharField(max_length=50),
        ),
    ]
